
package com.company.it.enterpriseserviceimplservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EnterpriseService", targetNamespace = "http://it.company.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnterpriseService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.company.it.enterpriseserviceimplservice.CheckByEmailResponse
     */
    @WebMethod
    @WebResult(name = "checkByEmailResponse", targetNamespace = "http://it.company.com/", partName = "parameters")
    public CheckByEmailResponse checkByEmail(
        @WebParam(name = "checkByEmail", targetNamespace = "http://it.company.com/", partName = "parameters")
        CheckByEmail parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.company.it.enterpriseserviceimplservice.CheckByIDResponse
     */
    @WebMethod
    @WebResult(name = "checkByIDResponse", targetNamespace = "http://it.company.com/", partName = "parameters")
    public CheckByIDResponse checkByID(
        @WebParam(name = "checkByID", targetNamespace = "http://it.company.com/", partName = "parameters")
        CheckByID parameters);

}
