
package com.company.it.enterpriseserviceimplservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EnterpriseServiceImplService", targetNamespace = "http://it.company.com/", wsdlLocation = "EnterpriseServiceImplService.wsdl")
public class EnterpriseServiceImplServiceClient
    extends Service
{

    private final static URL ENTERPRISESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.company.it.enterpriseserviceimplservice.EnterpriseServiceImplServiceClient.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.company.it.enterpriseserviceimplservice.EnterpriseServiceImplServiceClient.class.getResource(".");
            url = new URL(baseUrl, "EnterpriseServiceImplService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'EnterpriseServiceImplService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ENTERPRISESERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public EnterpriseServiceImplServiceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnterpriseServiceImplServiceClient() {
        super(ENTERPRISESERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://it.company.com/", "EnterpriseServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns EnterpriseService
     */
    @WebEndpoint(name = "EnterpriseServiceImplPort")
    public EnterpriseService getEnterpriseServiceImplPort() {
        return super.getPort(new QName("http://it.company.com/", "EnterpriseServiceImplPort"), EnterpriseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnterpriseService
     */
    @WebEndpoint(name = "EnterpriseServiceImplPort")
    public EnterpriseService getEnterpriseServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://it.company.com/", "EnterpriseServiceImplPort"), EnterpriseService.class, features);
    }

}
